version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: user-service
    AWS_REGION: us-east-1

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - mvn --version

  pre_build:
    commands:
      - echo Logging in to ECR
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION # first 7 characters of the commit hash
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build Spring Boot jar
      - mvn clean package -DskipTests
      - echo Building Docker image
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image to ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image detail file
      - printf '{"image":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json